### ISSUE TITLE
마이페이지: 개인정보 조회/수정 개발

### ISSUE THREAD

**Issue by cw-y** [Sidenow-Team2/freshgreenish-back#39]
# Description
마이페이지 내 프로필 페이지: 개인정보 조회/수정 기능 개발

# TODO
- [ ] 이메일 인증
- [ ] 개인정보 조회
- [ ] 개인정보 수정
- [ ] 기본배송지 조회/변경
- [ ] 예외처리: 닉네임 중복

# ETC
- [ ] API 문서 수정하기

**Comment by cw-y** [comment]
* 이메일 인증 화면

![image](https://github.com/Sidenow-Team2/freshgreenish-back/assets/62734887/f95b0541-46d9-40d4-b607-d4acec107e26)

**Comment by cw-y** [comment]
- 세션 관리 (httpSession)
- 개인정보에 접근하기 전에 이메일 인증 화면이 먼저 뜨고, 인증 완료될 경우 수정 화면으로 이동하는 것
 => 현재는 수정기능마다 일일이 인증했는지 확인중
- 로컬 이미지 화면에 띄우기 (`<img th:src=@{}>`)
- 이미지 크기 예외처리 (허용 이미지사이즈 초과)
